<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Loops (Need) Exercises</span></div>

<span style="font-weight:bolder;font-size:1.25em">Exercise 1 (Celsius to Fahrenheit) 

In [1]:
temperatures_celsius = [
    0, 5, 10, 15, 20, 25,
    30, 35, 40, 45, 50
]

In [4]:
import numpy as np

temp_c = np.array(temperatures_celsius)
temp_f = (temp_c * 1.8) + 32
temp_f

array([ 32.,  41.,  50.,  59.,  68.,  77.,  86.,  95., 104., 113., 122.])

<span style="font-weight:bolder;font-size:1.25em">Exercise 2 (Multiplication table) 

In [37]:
for letter in ['A', 'B', 'C']:
    for number in [1, 2, 3]:
        print(f'{letter}{number}', end='\t')     # '\t' adds a tab after each number
    print('\n')                                  # '\t' adds a tab after each letter row

A1	A2	A3	

B1	B2	B3	

C1	C2	C3	



In [38]:
for index in [1, 2, 3, 4, 5]:
    print(f'{index} :', end='\t')
    for multiple in [1, 2, 3, 4, 5]:
        timestable = index*multiple
        print(f'{timestable}', end='\t')
    print()

1 :	1	2	3	4	5	
2 :	2	4	6	8	10	
3 :	3	6	9	12	15	
4 :	4	8	12	16	20	
5 :	5	10	15	20	25	


<span style="font-weight:bolder;font-size:1.25em">Exercise 3 (Simulating a Coin Flip Experiment)  

In [44]:
coin = np.array(np.random.rand(10))
coin

array([0.32802412, 0.13760941, 0.22126191, 0.78101559, 0.52946637,
       0.88205433, 0.8577352 , 0.17814356, 0.66070332, 0.38152691])

In [45]:
head = coin > 0.5
head

array([False, False, False,  True,  True,  True,  True, False,  True,
       False])

In [131]:
for index in range(1, 11):
    coin = np.array(np.random.rand(10))
    head = np.where(coin > 0.5, 1, coin)
    heads = int(head[head == 1].sum())
    print(f'Experiment {index}: No. of Heads = {heads}')

Experiment 1: No. of Heads = 7
Experiment 2: No. of Heads = 4
Experiment 3: No. of Heads = 4
Experiment 4: No. of Heads = 3
Experiment 5: No. of Heads = 5
Experiment 6: No. of Heads = 5
Experiment 7: No. of Heads = 5
Experiment 8: No. of Heads = 5
Experiment 9: No. of Heads = 1
Experiment 10: No. of Heads = 8
