<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

In [13]:
py_list=[1,2,3,4,5]

#good for stoping numbers

In [10]:
py_list

[1, 2, 3, 4, 5]

In [11]:
import numpy as np
np_array = np.array([1,2,3,4,5])

# np.array is useful for math calculations

In [12]:
np_array

array([1, 2, 3, 4, 5])

## Testing the fucntion

In [17]:
py_list*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [18]:
np_array*2

array([ 2,  4,  6,  8, 10])

## Fucntion of np_array to be for math

In [21]:
py_list+2

TypeError: can only concatenate list (not "int") to list

In [20]:
np_array+2

array([3, 4, 5, 6, 7])

## ???

In [22]:
np_array.shape

(5,)

In [24]:
'a' in ['a','b','c']

True

In [27]:
my_rand_numbers=np.random.randint(1,100,100)
my_rand_numbers

array([47, 67, 60, 41,  3, 96, 17, 66, 93, 74, 10,  5, 35, 47, 87, 12, 22,
       52, 22, 13, 34, 89, 54, 91, 90, 73, 15, 54, 66, 30, 46, 66, 15,  5,
       48, 74, 56,  3, 43,  1, 63, 26, 80, 31, 33, 84, 74, 45,  1, 88, 69,
       23, 33, 21, 43, 89, 15, 11, 59, 66, 71, 43, 67, 90, 51, 67, 55,  2,
       10, 93, 96, 38, 44,  1, 39, 83, 68, 76, 34, 65, 50, 38,  3, 33, 18,
       37, 44,  4, 99, 34, 63, 18, 36,  9, 93, 61, 47, 89, 84, 15],
      dtype=int32)

In [31]:
masked = my_rand_numbers < 50 

In [32]:
my_rand_numbers[masked]

# "[]" is asked to get a subset of the initial set

array([47, 41,  3, 17, 10,  5, 35, 47, 12, 22, 22, 13, 34, 15, 30, 46, 15,
        5, 48,  3, 43,  1, 26, 31, 33, 45,  1, 23, 33, 21, 43, 15, 11, 43,
        2, 10, 38, 44,  1, 39, 34, 38,  3, 33, 18, 37, 44,  4, 34, 18, 36,
        9, 47, 15], dtype=int32)

In [48]:
#Subsection that is below 50 and is odd

mask_odd = (my_rand_numbers < 50) & (my_rand_numbers%2==1)

# "&" to add a second condition

In [44]:
my_rand_numbers[mask_odd]

array([47, 41,  3, 17,  5, 35, 47, 13, 15, 15,  5,  3, 43,  1, 31, 33, 45,
        1, 23, 33, 21, 43, 15, 11, 43,  1, 39,  3, 33, 37,  9, 47, 15],
      dtype=int32)

In [56]:
# types of divide
10/3

# typical division

3.3333333333333335

In [55]:
10//3

# will give the whol number from the division

3

In [54]:
10%3

# this will give you the remiainer after all integers are remvoed

1

In [46]:
#extraction of specific number e.g. I want the 5th number

my_rand_numbers[5]

np.int32(96)

In [47]:
#extraction of specific number e.g. I want the second last number

my_rand_numbers[-2]

np.int32(84)

In [57]:
py_2d_list = [[1,2,3],[4,5,6],[7,8,9]]

In [59]:
py_2d_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [60]:
py_2d_list[2]

[7, 8, 9]

In [61]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [63]:
py_list_2d

[[1, 'A'],
 [2, 'B'],
 [3, 'C'],
 [4, 'D'],
 [5, 'E'],
 [6, 'F'],
 [7, 'G'],
 [8, 'H'],
 [9, 'I'],
 [10, 'J']]

In [66]:
py_list_2d[0]

[1, 'A']

In [72]:
py_list_2d[0][1]

'A'

In [65]:
np_array_2d

#restriction on numpy i sthat there is only 1 format, so by using array, the number will be converted to words which is represented by ''

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C'],
       ['4', 'D'],
       ['5', 'E'],
       ['6', 'F'],
       ['7', 'G'],
       ['8', 'H'],
       ['9', 'I'],
       ['10', 'J']], dtype='<U21')

In [68]:
np_array_2d[0]

array(['1', 'A'], dtype='<U21')

In [69]:
np_array_2d[0,1]

np.str_('A')

In [96]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

dict_superhero_info = {
    "Natasha Romanoff": ["Black Widow", "Natalia"],
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

In [97]:
superhero_info['Tony Stark']

'Iron Man'

In [98]:
superhero_info['Natasha Romanoff']

'Black Widow'

In [99]:
superhero_info['Natasha Romanoff'][0]

'B'

# Need

In [100]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  # OR
x = np_array

In [101]:
py_list[-1]

'j10'

In [107]:
py_list[3:6]

['d4', 'e5', 'f6']

In [113]:
py_list[-1::1]

['j10']

# What to expect in this chapter

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

## 1.2 Accessing data from a list (or array)

## 1.3 Accessing data from a dictionary

## 1.4 Higher dimensional lists

# 2 Lists vs. Arrays

## 2.1 Size

## 2.2 Arrays are fussy about type

## 2.3 Adding a number

## 2.4 Adding another list

## 2.5 Multiplying by a Number

## 2.6 Squaring

## 2.7 Asking questions

## 2.8 Mathematics

## Footnotes