<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

<span style="font-weight:bolder;font-size:1.25em"> I am redoing the exercises here

# Exercise 2

In [20]:
import numpy as np

np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

In [21]:
index = np_array_2d[:11, 0]
num = index.astype(int)
mask = num%2 > 0 
np_array_2d[mask,1]

# mask = np_array_2d % 2 != 0

array(['A', 'C', 'E', 'G', 'I'], dtype='<U21')

In [49]:
nums = np_array_2d[:10, 0]
nums = nums.astype(int)
np_array_2d[nums%2==1, 1]

array(['A', 'C', 'E', 'G', 'I'], dtype='<U21')

# Exerise 3

In [99]:
array = np.array([[66, 50, 57, -1, -1],
                  [92, -1, 88, -1, -1],
                  [75, -1, -1, 76, -1],
                  [-1, 51, 87, -1, -1],
                  [71, -1, 67, -1, 69]])
array[array < 50] = -1
array[array > 50] = +1
array[array == 50] = 0

print(array)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]


# Loop (good)

In [68]:
for number in range(9):
    if number % 2 == 1:
        odd = number**2
    else:
        continue
    print(odd)

1
9
25
49


In [63]:
odd = [number**2 for number in range(9) if number % 2 == 1]
odd

[1, 9, 25, 49]

In [2]:
%%timeit 

for number in range(9):
    if number % 2 == 1:
        odd = number**2
    else:
        continue

1.98 μs ± 151 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [4]:
%%timeit
odd = [number**2 for number in range(9) if number % 2 == 1]

2.14 μs ± 280 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [10]:
waste = 100
year = 0

while waste > 50:
    year += 1
    waste *= 0.95
    if waste <= 50: break

year

14

In [25]:
co2_data = np.array([(2000, 369.55), (2001, 371.14), (2002, 373.28), 
                     (2003, 375.80), (2004, 377.52), (2005, 379.80), 
                     (2006, 381.90), (2007, 383.79), (2008, 385.60), 
                     (2009, 387.43), (2010, 389.90), (2011, 391.65), 
                     (2012, 393.85), (2013, 396.52), (2014, 398.65),
                     (2015, 400.83), (2016, 404.24), (2017, 406.55), 
                     (2018, 408.52), (2019, 411.44), (2020, 414.24)
                    ])

year = co2_data[:, 0]

for i in co2_data:
    diff = i+1,1] - co2_data[i,1]
    diff

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [50]:
# Failed code

co2_data = [
    (2000, 369.55), (2001, 371.14), (2002, 373.28), 
    (2003, 375.80), (2004, 377.52), (2005, 379.80), 
    (2006, 381.90), (2007, 383.79), (2008, 385.60), 
    (2009, 387.43), (2010, 389.90), (2011, 391.65), 
    (2012, 393.85), (2013, 396.52), (2014, 398.65),
    (2015, 400.83), (2016, 404.24), (2017, 406.55), 
    (2018, 408.52), (2019, 411.44), (2020, 414.24)
]

for i in co2_data:
    year, co2 = i.split(',')                 # co2_data is tuples, cannot be split like this
    diff = (i+1)[1] - i[1]                   # ngl this doesnt make sense.... like what is the point of splitting HAHAHAHAHA
    if diff > 3:
        print(f'in years {i[0]} and {i+1[0]}, there was a increase of CO<subs>2 increase of more than 3ppm')

<>:17: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
<>:17: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
C:\Users\junhe\AppData\Local\Temp\ipykernel_35956\238145807.py:17: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
  print(f'in years {i[0]} and {i+1[0]}, there was a increase of CO<subs>2 increase of more than 3ppm')


AttributeError: 'tuple' object has no attribute 'split'

In [51]:
co2_data = [
    (2000, 369.55), (2001, 371.14), (2002, 373.28), 
    (2003, 375.80), (2004, 377.52), (2005, 379.80), 
    (2006, 381.90), (2007, 383.79), (2008, 385.60), 
    (2009, 387.43), (2010, 389.90), (2011, 391.65), 
    (2012, 393.85), (2013, 396.52), (2014, 398.65),
    (2015, 400.83), (2016, 404.24), (2017, 406.55), 
    (2018, 408.52), (2019, 411.44), (2020, 414.24)
]

for i in range(len(co2_data)):
    if co2_data[i][0] < 2020: 
        y1, co1 = co2_data[i]
        y2, co2 = co2_data[i+1]
        diff = co2 - co1
        if diff > 3:
            print(f'In years {y1} and {y2}, there was a increase of CO₂ increase of more than 3ppm')

In years 2015 and 2016, there was a increase of CO₂ increase of more than 3ppm


# Functions (good)

In [70]:
def convert_celsius(temp, target_scale):
    if isinstance(temp, float):
        print('Please input a number!')
    else:
        scale = target_scale.lower()
        if 'k' in scale:
            new_temp = temp + 273.15
            print(f'{temp}°C is {new_temp:.2f}K')
        elif 'f' in scale:
            new_temp = (temp * 9/5) + 32
            print(f'{temp}°C is {new_temp:.2f}°F')
        else:
            print('Wrong Scale provided!')               

In [78]:
convert_celsius(-90, 'Kelvin')

-90°C is 183.15K


In [82]:
convert_celsius(-90, 'faren')

-90°C is -130.00°F


In [86]:
def convert_fahrenheit(temp, target_scale):
    if isinstance(temp, float):
        print('Please input a number!')
    else:
        scale = target_scale.lower()
        if 'k' in scale:
            new_temp = (temp-32) * 5/9 + 273.15
            print(f'{temp}°F is {new_temp:.2f}K')
        elif 'c' in scale:
            new_temp = (temp-32) * 5/9
            print(f'{temp}°F is {new_temp:.2f}°C')
        else:
            print('Wrong Scale provided!')               

In [87]:
def convert_temperature(temp, source, target_scale):
    if isinstance(temp, float):
        print('Please input a number!')
    else:
        source = source.lower() 
        scale = target_scale.lower()
        if 'c' in source:
            convert_celsius(temp, target_scale)
        elif 'f' in source:
            convert_fahrenheit(temp, target_scale)
        elif 'k' in source:
            if 'f' in scale:
                new_temp = (temp-273.15) * 9/5 + 32
                print(f'{temp}°F is {new_temp:.2f}K')
            elif 'c' in scale:
                new_temp = temp - 273.15
                print(f'{temp}°F is {new_temp:.2f}°C')
            else:
                print('Wrong Scale provided!') 
        else:
            print('Wrong source scale provided!')  

In [93]:
convert_temperature(90, 'k', 'F')

90°F is -297.67K


In [92]:
convert_temperature(90, 'k', 'j')

Wrong Scale provided!


In [91]:
convert_temperature(90, 'grees', 'c')

Wrong source scale provided!
